eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost
spring:
  application:
    name: gateway2
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
  data:
    mongodb:
      database: user_db
      port: 27017
server:
  port: 8050
jwt:
  secret: 394ujew2398
